apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: arch-dev-test
  region: us-east-1

vpc:
  subnets:
    private:
      us-east-1a: 
        id: subnet-092d03b234eb5ebbe
      us-east-1b:
        id: subnet-01419f23723e3c474
      us-east-1c:
        id: subnet-0db326c88e6531600

managedNodeGroups:
  - name: arch-dev-test-ng-default
    desiredCapacity: 2
    instanceType: t3.small
    privateNetworking: true
    tags:
      Name: arch-dev-test-eks-mng
      owner: gabriel.brotas@wexinc.com
      approle: eks
      appid: arch-dev-test-eks-mng
      billingid: WCORP-90330-9910-90000
      NOSCHEDULE: EKS
