# ---
# apiVersion: v1
# kind: Secret
# type: kubernetes.io/dockerconfigjson
# metadata:
#   name: gh-secrets
#   namespace: argocd
# data:
#   .dockerconfigjson: {{ .Values.github.dockerpat }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: gh-secrets
  namespace: default
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJaMkZpY21sbGJDMWljbTkwWVhNNloyaHdYMmd4U1ZaelQxRkZaM281VGpGT2FrSkhiVWR1UTNGNWNVRlJWV1JxYURCRGMxcHRVZz09IgogICAgfQogIH0KfQo=
