---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: gh-secrets
  namespace: {{ .Release.Namespace | quote }}
data:
  .dockerconfigjson: {{ .Values.GH_DOCKER_ACCESS_TOKEN }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: backstage-secrets
  namespace: {{ .Release.Namespace | quote }}
data:
  AUTH_GITHUB_CLIENT_ID: {{ .Values.AUTH_GITHUB_CLIENT_ID }}
  AUTH_GITHUB_CLIENT_SECRET: {{ .Values.AUTH_GITHUB_CLIENT_SECRET }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: postgres-secrets
  namespace: {{ .Release.Namespace | quote }}
data:
  pg-host: {{ .Values.pg.host }}
  pg-user: {{ .Values.pg.user }}
  pg-password: {{ .Values.pg.password }}cd
